### ISSUE TITLE
Why day 0 is 2020-01-22 ?

### ISSUE THREAD

**Issue by lazaronixon** [katanaml/covid19#2]
Why date step 1 is 2020-01-22 for all countries? shouldn't  it be the day of first case ?

**Comment by abaranovskis-redsamurai** [comment]
Day 2020-01-22 is returned as first day by REST API for all countries, I presume this is when data started to be tracked globally. I'm using it as a start day for all countries because it helps to visualize and compare the situation visually.

**Comment by abaranovskis-redsamurai** [comment]
On the second thought - I will add your suggestion to v2. Will display chart data from 1st case.

**Comment by lazaronixon** [comment]
I told you this because it change de forecast

**Comment by abaranovskis-redsamurai** [comment]
I will keep it for the forecast from Jan 22 for all countries - I believe it is important to include 0 (this will help to draw a steeper curve, when suddenly infections start to appear), but on UI will show chart from the day with the first infection (just to render better chart).

**Comment by lazaronixon** [comment]
Do you think I can use this model to forecast deaths?

**Comment by abaranovskis-redsamurai** [comment]
Yes, I think so. In the next 2 days I will publish v2, with additional equation and backtesting. You should wait, it will give more insight for the forecast
