### ISSUE TITLE
[Question] How do I run the Web UI app?

### ISSUE THREAD

**Issue by sanzgiri** [katanaml/covid19#3]
Hi Andrej,  thanks for open-sourcing the code for your covid-19 forecasting app! I was able to easily adapt and run it the schedule to generate forecasts for states in India. The question I have is whether it is possible to run the Web UI with the code in this repo? If yes, could you provide the instructions to do this? 

Thanks,
Ashutosh

**Comment by abaranovskis-redsamurai** [comment]
Hi Ashutosh,

I have updated README file with UI instructions: https://github.com/katanaml/covid19#ui-instructions

Thanks for asking!

Andrej
